---
title: "National Parks"
author: "Reagan Thomey rt24549"
date: "10/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Introduction

The datasets I chose for this project consist of information regarding national parks, unemployment rate, and gas prices. The national park dataset contains annual visitation numbers for each park from 1904 to 2016 in addition to the state and region the park resides in, its geometry, and ID number. The Unemployment dataset contains the percentage of unemployment for each year from 1941-2010 in addition to other information regarding population numbers, labor force, and percentage of employment. The gas prices dataset contains average gas prices in the US from the years 1929-2015. These datasets were acquired from github.com and datahub.io when searching for national park information and annual unemployment rates. I chose these datasets because I'm interested in national parks, and one day I wish to travel to all of them, so my search started out by finding information on national parks. I then expanded it to unemployment rate and gas price because I was interested to see if there was any correlation between them and the amount of people that visited the parks. I expect to see some association between different levels of unemployment and park visitors, and also a possible association between the price of gas and park visitors.


###Joining the Datasets

After uploading the datasets into my environment, the year column for the "employed" and "park_visits" datasets needed to be changed to a numeric so that both columns were compatible to join. The "gas_price" and "unemployment" dataset were altered by taking out extra columns that were not relevant in what I wanted to test. All three datasets were joined using inner_join because I only wanted rows that matched by year across all three datasets, so my resulting data did not have new NAs introduced. The only cases that were dropped were ones outside of the year 1941-2010. The dropping of those cases may potentially affect how strong the corellations between the numeric values are, but there should be enough data in the resulting dataset so that the absence of those cases is not substantial.

```{R}
library(tidyverse)
park_visits <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/national_parks.csv")
gas_price <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/gas_price.csv")
unemployment<-readr::read_csv("https://pkgstore.datahub.io/core/employment-us/aat1_csv/data/d7e5ec6ea0340e846fd84ae6a69519c2/aat1_csv.csv")

gprice<-gas_price%>%select(-gas_constant)
unemployed<-unemployment%>%select( "year", "unemployed_percent")
unemployed$year<- as.numeric(as.character(unemployed$year))
park_visits$year<- as.numeric(as.character(park_visits$year))
mydata<-unemployed%>%inner_join(park_visits)%>%inner_join(gprice)
glimpse(mydata)
```


###Wrangling

After the dataset was joined, I filtered out the observations to only show "National Parks", and I removed irrelevant columns to make the data easier to read. I then arranged the data alphabetically by the park name and by descending year to show more recent years at the top. A new variable was created from the "unemployed_percent" to show the unemployment rate as a category, so it is easier to distinguish if that year had a low, normal, or high unemployment rate.

```{R}
mydata<-mydata%>%filter(str_detect(unit_type,"National Park"),unit_type=="National Park")
mydata<-mydata%>%select(-metadata, -number_of_records, -unit_code)
mydata<-mydata%>%arrange(unit_name, desc(year))
mydata<-mydata%>%
  mutate(unemployment_cat = case_when(unemployed_percent>7 ~ "high",
                                      unemployed_percent<=7 & 4<=unemployed_percent ~ "normal",
                                      unemployed_percent<4 ~ "low"))
glimpse(mydata)

```


The summary statistics resulted in Great Smoky Mountains National Park has the highest average number of visitors across all years, and also the highest number of variance and standard deviation. Across the different unemployment rates, higher unemployment rates resulted in a higher average number of visitors across all parks. This could be due to the fact that more people do not have a job they have to report to, so they have time to go to a national park.The state of California has the most observations of national parks, but North Carolina has the largest average number of visitors at the parks that reside in that state. The summary statistics for the data grouped by state was spread wider using pivot_wider so that each state corresponds to an individual value for each statistic, and then the data was gathered using pivot_longer to tidy the data so that there are only two columns. Summary statistics for the data overall revealed that the average unemployment rate is 5.6%, the average number of visitors is 851,028,and the 80th percentile of visitors is 1,056,273 with the unemployment rate being 6.8% and the price of gas being $1.19. There are also low correlations between number of visitors and unemployment percent and between visitors and gas prices being 0.0969 and 0.145, respectively.

```{R}
mydata %>%
  group_by(unit_name,state) %>%
  summarize(mean_visitors=mean(visitors,na.rm=T), 
            sd_visitors=sd(visitors, na.rm=T),n(),var_visitors=var(visitors,na.rm=T),
            min_visitors=min(visitors,na.rm=T),max_visitors=max(visitors,na.rm=T),
            median_visitors=median(visitors,na.rm=T))%>%arrange(desc(mean_visitors))%>%tibble
mydata %>%
  group_by(unemployment_cat) %>%
  summarize(mean_visitors=mean(visitors,na.rm=T), 
            sd_visitors=sd(visitors, na.rm=T),n(),var_visitors=var(visitors,na.rm=T),
            min_visitors=min(visitors,na.rm=T),max_visitors=max(visitors,na.rm=T),
            median_visitors=median(visitors,na.rm=T))%>%tibble
mydata%>%group_by(state)%>%summarize(mean_visitors=mean(visitors,na.rm=T), 
                                     sd_visitors=sd(visitors, na.rm=T),n_=n(),var_visitors=var(visitors,na.rm=T),
                                     min_visitors=min(visitors,na.rm=T),max_visitors=max(visitors,na.rm=T),
                                     median_visitors=median(visitors,na.rm=T))%>%
                 pivot_wider(names_from="state", values_from=contains("_"))%>%pivot_longer(contains("_"))%>%tibble


mydata%>%
  summarize_if(is.numeric, mean,na.rm=T)%>%tibble
mydata%>%
  summarize_if(is.numeric, sd,na.rm=T)%>%tibble
mydata%>%
  summarize_if(is.numeric, min,na.rm=T)%>%tibble
mydata%>%
  summarize_if(is.numeric, quantile,na.rm=T)%>%tibble
mydata%>%
  summarize_if(is.numeric, max,na.rm=T)%>%tibble
mydata%>%
  summarize_if(is.character, n_distinct)%>%tibble
mydata%>%
  summarize(cor(visitors,unemployed_percent,use = "pair"))%>%tibble
mydata%>%
  summarize(cor(visitors,gas_current,use = "pair"))%>% tibble

```

###Visualizing

The correlation heatmap shows that there is a slightly stronger correlation between unemployment rate and gas prices, but overall, there are no significant correlations found between the numeric variables in the dataset. All correlations reside closer to to zero, so the correlation is weak. 

```{R}

mydata%>%select(-year)%>%select_if(is.numeric)%>%cor%>%as.data.frame%>% rownames_to_column%>%pivot_longer(-1)%>%
  ggplot(aes(rowname,name,fill=value))+geom_tile()+
  geom_text(aes(label=round(value,2)))+
  xlab("")+ylab("")+coord_fixed()
```

The plot of the relationship of park visitors and unemployment rate shows that only higher numbers of visiors occur when the unemployment rate is normal or high. This could mean that people choose to visit national parks when they have more time to do so. Another trend seen in the graph is that most visitors are under 4,000,000 regardless of the unemployment rate which is why there was no correlation seen in the previous heatmap between the two variables.
```{R}
options(scipen=999)
ggplot(mydata, aes(visitors,unemployed_percent))+
  geom_point(aes(color=unit_name),size=0.8,stat="summary")+theme_minimal()+theme(legend.position="none")+
  ggtitle("National Park Visits Amongst Unemployment") + ylab("Percentage of Unemployment") + xlab("Visitors")+
  scale_x_continuous(breaks=seq(0,10000000,1000000))+scale_y_continuous(breaks=seq(0,10,1))+theme(axis.text.x=element_text(angle=45, hjust=1))
```

The plot of the relationship between unemployment rate and gas prices shows that gas prices are at there highest in normal and higher unemployment rates. Inflation has played a huge role in the price of gas which is why it was so low 80 years ago in addition to having lower unemployment rates. The lack of a strong relationship in the plot demonstrates how there is a low correlation between these two variables which is also seen in the heatmap above.

```{R}
options(scipen=999)
ggplot(mydata, aes(x=unemployed_percent,y=gas_current,fill=unemployment_cat))+
  geom_bar(stat="summary")+
  geom_errorbar(stat="summary")+theme_dark()+ggtitle("Unemployment Rate and Gas Prices") + 
  ylab("Price of Gas (dollars)") + xlab("Percent of Unemployment")+labs(fill="Unemployment Rate")+
  scale_fill_brewer(palette = "Purples")+scale_x_continuous(breaks=seq(0,10,1))+scale_y_continuous(breaks=seq(0,3,0.5))
```

###Dimensionality Reduction

The first two PCs account for 72% of total variability. A scree plot was created to deterine how many PCs to keep, and the resulting plot showed that only the first one should be kept because after the first one, that is when the scree plot begins to flatten. In PC1, gas prices have the highest score compared to the other two numeric variables meaning that there is greater variance in gas prices. in PC2, percentage of unemployment is higher than gas prices so there is greater variance in unemployment than there is in gas prices. In PC3, percentage of unemployment is higher than visitors which indicates that there is greater variance in unmployment than there is in number of visitors of the parks. The Great Smoky Mountains National Park scored the highest in PC1 and PC3 and the lowest in PC2. The Capitol Reef National Park scored the lowest on PC1, and the Kobuk Valley National Park scored the highest in PC2 and the lowest in PC3. The plot of loadings reveals that percentage of unemployment and gas prices contribute more to the variations in PC2, while visitors contributes to the variations in PC1.

```{R}
mydata_pca1<-mydata%>%select(unit_name,unemployed_percent,visitors,gas_current)
mydata_nums<-mydata_pca1 %>% select_if(is.numeric) %>% scale
rownames(mydata_nums)<-mydata_pca1$unit_name
mydata_pca2<-princomp(mydata_nums)
names(mydata_pca2)
summary(mydata_pca2, loadings=T)
1.1831456+ 0.9646265 +0.8178268
(1.1831456+ 0.9646265)/2.9655
eigval<-mydata_pca2$sdev^2 
varprop=round(eigval/sum(eigval), 2) 
ggplot() + geom_bar(aes(y=varprop, x=1:3), stat="identity") + xlab("") + geom_path(aes(y=varprop, x=1:3)) + 
  geom_text(aes(x=1:3, y=varprop, label=round(varprop, 2)), vjust=1, col="white", size=5) + 
  scale_y_continuous(breaks=seq(0, .6, .2), labels = scales::percent) + 
  scale_x_continuous(breaks=1:10)



mydata_df<-data.frame(PC1=mydata_pca2$scores[, 1], PC2=mydata_pca2$scores[, 2])
ggplot(mydata_df, aes(PC1, PC2)) + geom_point()
mydata_pca2$scores[,1:3] %>% as.data.frame %>% top_n(3, Comp.1)
mydata_pca2$scores[,1:3] %>% as.data.frame %>% top_n(-3, Comp.1)
mydata_pca2$scores[,1:3] %>% as.data.frame %>% top_n(3, wt=Comp.2)
mydata_pca2$scores[,1:3] %>% as.data.frame %>% top_n(3, wt=desc(Comp.2))
mydata_pca2$scores[,1:3] %>% as.data.frame %>% top_n(3, Comp.3)
mydata_pca2$scores[,1:3] %>% as.data.frame %>% top_n(-3, Comp.3)
mydata_pca1 %>% filter(unit_name%in%c("Great Smoky Mountains National Park"))
mydata_pca1 %>% filter(unit_name%in%c("Capitol Reef National Park","Denali National Park ","Denali National Preserve "))
mydata_pca1 %>% filter(unit_name%in%c("Kobuk Valley National Park ","Lake Clark National Park  ","National Park of American Samoa "))
mydata_pca1 %>% filter(unit_name%in%c("Great Smoky Mountains National Park"))
mydata_pca2$loadings[1:3, 1:2] %>% as.data.frame %>% rownames_to_column %>%
  ggplot() + geom_hline(aes(yintercept=0), lty=2) +
  geom_vline(aes(xintercept=0), lty=2) + ylab("PC2") + xlab("PC1") +
  geom_segment(aes(x=0, y=0, xend=Comp.1, yend=Comp.2), arrow=arrow(), col="red") +
  geom_label(aes(x=Comp.1*1.1, y=Comp.2*1.1, label=rowname))

```







```

